server:
  port: 8083

spring:
  application:
    name: analytics-consumer
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  cloud:
    aws:
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:http://localhost:4566}
      region:
        static: ${AWS_REGION:ap-south-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}

app:
  sqs:
    analytics-queue-name: ${ANALYTICS_QUEUE_NAME:analytics-queue}

logging:
  level:
    com.shanmugapriya.analyticsconsumer: DEBUG
